version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    command: >
        bash -c "python manage.py migrate &&
                 gunicorn stripe_api.wsgi:application --bind 0:8000"
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
