version: '3.5'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 3
  web:
    build: .
    command: >
         bash -c "python manage.py migrate &&
                  python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
        db:
          condition: service_healthy
    env_file:
      - ./.env
