# Generated by Django 4.1.3 on 2022-11-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Discount',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='USD', max_length=5, verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
